#+Title: Superfly's GNU Emacs config
#+AUTHOR: Superfly Johnson
#+DESCRIPTION: Superfly's personal Emacs config.
#+STARTUP: showeverything
#+auto_tangle: t

* TABLE OF CONTENTS                                                   :TOC_2:
- [[#description][Description]]
- [[#important-put-this-in-your-initel][IMPORTANT: Put this in your init.el]]
- [[#installation][Installation]]
  - [[#linux][Linux]]
  - [[#windows][Windows]]
- [[#requirements][Requirements]]
  - [[#package-archives][Package Archives]]
  - [[#use-package][Use-Package]]
- [[#theming][Theming]]
- [[#org-mode][Org-mode]]
  - [[#tables-of-content][Tables of Content]]
  - [[#auto-tangle][Auto-Tangle]]
- [[#miscellaneous][Miscellaneous]]
  - [[#magit][Magit]]
- [[#customization][Customization]]
  - [[#evil-mode][EVIL mode]]
  - [[#electricicity][Electricicity]]
  - [[#tabulation][Tabulation]]
  - [[#hooks][Hooks]]
- [[#additional-code-modes][Additional Code Modes]]
  - [[#nix-mode][Nix-Mode]]
  - [[#systemd-mode][SystemD-Mode]]
  - [[#pug-mode][Pug-Mode]]
  - [[#powershell-mode][Powershell-Mode]]

* Description
This is my personal GNU Emacs configuration. It comes with a little install script that I use when installing on a new machine.
* IMPORTANT: Put this in your init.el
#+BEGIN_SRC emacs-lisp :tangle init.el
(org-babel-load-file
 (expand-file-name
  "config.org"
  user-emacs-directory))
#+END_SRC

* Installation
** Linux
To install the new configuration, simply execute ./install.sh.
#+BEGIN_SRC sh :tangle install.sh :shebang "#!/bin/sh" :tangle-mode (identity #o700)
  EMACSDIR="$HOME/.emacs.d"
  if [ ! -d ${EMACSDIR} ]
  then
    echo "${EMACSDIR} doesn't exist. Creating it..."
    mkdir ${EMACSDIR}
  fi
  for f in init.el config.org; 
    do echo "Symlinking ${f} to ${EMACSDIR}/${f}";
    ln -sf $(readlink -f ${f}) $EMACSDIR/${f};
  done
#+END_SRC
** Windows
 #+begin_src ps :tangle install.ps1
if (-not (Get-Item $env:appdata/.emacs.d)){
  Write-Host "Configuration directory doesn't exist, creating it..."
  New-Item -Path "$env:appdata/.emacs.d" -ItemType directory
}
foreach ($i in @("init.el","config.org")){
  Write-Host "Copying $i to $env:appdata/.emacs.d"
  Copy-Item $i "$env:appdata/.emacs.d"
}
 #+end_src
* Requirements
The configuration has some dependencies. This section is dedicated to that.

** Package Archives
This adds MELPA to our package archives

#+BEGIN_SRC emacs-lisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
#+END_SRC

** Use-Package
We use "use-package" to set depdencies and configure modules more easily. ":ensure t" globally makes it so that packages within "use-package" keywords are automatically installed if they are missing.

#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (setq use-package-always-ensure t)
#+END_SRC

* Theming
This section is reserved for theming, if we ever add some.
#+BEGIN_SRC emacs-lisp
(if (eq system-type 'windows-nt)
  (set-face-attribute 'default nil :family "Consolas" :height 110)
)
#+END_SRC

* Org-mode
** Tables of Content
I use toc-org to automatically generate tables of content in Emacs org-mode.
#+BEGIN_SRC emacs-lisp
(use-package toc-org
  :ensure t
  :after org
  :hook (org-mode toc-org-mode)
)
#+END_SRC
** Auto-Tangle
#+BEGIN_SRC emacs-lisp
(use-package org-auto-tangle
  :ensure t
  :after org
  :hook (org-mode org-auto-tangle-mode)
)
#+END_SRC
* Miscellaneous
** Magit
Magit is a git integration within emacs.
#+BEGIN_SRC emacs-lisp
(use-package magit
:ensure t)
#+END_SRC
* Customization
This section is dedicated to the changes of how emacs behaves
** EVIL mode
EVIL is an extensible 'vi' emulation for emacs. Vi keybinds are universal and are generally useful when ssh-ing into remote machines, so I use them within my .emacs file so I do not forget them.
#+BEGIN_SRC emacs-lisp
(use-package evil
    :init
    (setq evil-want-keybinding nil)
    (evil-mode)
)
#+END_SRC
*** EVIL collection
EVIL collection is a collection of contributed packages that evil-ify various emacs packages.
#+BEGIN_SRC emacs-lisp
  (use-package evil-collection
    :after evil
    :ensure t
    :config
    (evil-collection-init))
#+END_SRC
** [#B] Electricicity
*** Electric pair
#+BEGIN_SRC emacs-lisp
(electric-pair-mode 1)
#+END_SRC
** Hooks
*** Javascript-mode hook
This sets the javascript tab size to 2 within javascript-mode.
#+begin_src emacs-lisp
(add-hook 'javascript-mode-hook '(lambda()(
    setq indent-tabs-mode t tab-width 2 js-indent-level 2)
))
#+end_src
* Additional Code Modes
This section is reserved for syntactical modes that emacs doesn't contain by default.
** Nix-Mode
#+BEGIN_SRC emacs-lisp
(use-package nix-mode
  :mode "\\.nix\\'")
#+END_SRC
** SystemD-Mode
#+BEGIN_SRC emacs-lisp
(use-package systemd
  :ensure t)
#+END_SRC

** Pug-Mode
This mode is used for pug (previously known as jade) templates.
#+begin_src emacs-lisp
  (use-package jade-mode
  :ensure t)
#+end_src


** Powershell-Mode
This is a mode for powershell on Microsoft Windows.
#+begin_src 
  (use-package powershell 
  :ensure t)
#+end_src
